name = "life-evolution-system-api"
main = "src/index.ts"
compatibility_date = "2026-03-20"

[vars]
CORS_ORIGIN = "http://localhost:5173"
ACCESS_MODE = "access"

[[d1_databases]]
binding = "DB"
database_name = "life_evolution_db"
database_id = "5fcc07a8-05cd-417d-9eda-f9b4926ef580"
